from typing import List, Optional
from app.models import VehiclePayload, ChargeCurvePointPayload

# .NET'ten gelecek olan gercek payload yapisini simule eden test payload'u
MOCK_NET_VEHICLE_PAYLOAD = VehiclePayload(
    id=1,
    slug="abarth_500e_hatchback_2024",
    brand="Abarth",
    model="500E",
    variant="hatchback",
    year=2024,
    battery_useable_kwh=42.2,
    battery_nominal_kwh=45.0,
    battery_chemistry="NMC",
    battery_thermal_management="Liquid",
    heat_pump=True,
    wltp_range_tel_km=250,
    wltp_range_teh_km=250,
    wltp_nominal_consumption_wh_km=180.0,
    wltp_vehicle_consumption_wh_km=180.0,
    co2_emissions_g_km=0,
    real_range_km=200,
    range_cold_city_km=180,
    range_cold_highway_km=130,
    range_cold_combined_km=150,
    range_mild_city_km=250,
    range_mild_highway_km=170,
    range_mild_combined_km=200,
    efficiency_wh_km=222.0,
    efficiency_cold_city_wh_km=234.0,
    efficiency_cold_highway_wh_km=324.0,
    efficiency_cold_combined_wh_km=281.0,
    efficiency_mild_city_wh_km=168.0,
    efficiency_mild_highway_wh_km=248.0,
    efficiency_mild_combined_wh_km=211.0,
    fastcharge_power_max_kw=85.0,
    fastcharge_power_avg_kw=60.0,
    fastcharge_time_mins=35,
    fastcharge_speed_kmh=340,
    ac_charge_power_kw=11.0,
    ac_charge_time_mins=255,
    ac_charge_speed_kmh=47,
    charging_voltage=400,
    charge_curve=[
        ChargeCurvePointPayload(soc=10, power_kw=85.0),
        ChargeCurvePointPayload(soc=30, power_kw=80.0),
        ChargeCurvePointPayload(soc=50, power_kw=65.0),
        ChargeCurvePointPayload(soc=80, power_kw=30.0),
        ChargeCurvePointPayload(soc=100, power_kw=10.0),
    ],
    top_speed_kmh=155,
    acceleration_0_100_kmh=7.0,
    engine_power_kw=113,
    engine_torque_nm=235,
    drive_type="FWD",
    body_type="Hatchback",
    segment="B",
    roof_load_kg=0,
    tow_weight_braked_kg=0,
    tow_weight_unbraked_kg=0,
    trunk_capacity_l=185,
    front_trunk_capacity_l=0,
    vehicle_length_mm=3632,
    vehicle_width_mm=1683,
    vehicle_height_mm=1527,
    wheelbase_mm=2322,
    curb_weight_kg=1410,
    gross_vehicle_weight_kg=1700,
    max_payload_kg=290,
    turning_circle_m=9.7,
    connector_type="CCS",
    vehicle_type="hatchback",
    drag_coefficient=0.30,
    frontal_area_m2=2.1,
    regen_max_power_kw=50.0
)
